<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CDN-YF-QUANH" name="getExample" tests="8" failures="1" timestamp="2 May 2017 03:02:08 GMT" time="2.899" errors="0">
  <testcase name="loginTest" time="1.779" classname="login.LoginTest"/>
  <testcase name="getExampleTest" time="0.033" classname="example.GetExample"/>
  <testcase name="deleteExampleTest" time="0.029" classname="example.DeleteExapmle"/>
  <testcase name="postExampleTest" time="0.059" classname="example.PostExample"/>
  <testcase name="putExampleTest" time="0.023" classname="example.PutExample"/>
  <testcase name="getBicycleInfoTest" time="0.04" classname="store.BicycleInfoTest"/>
  <testcase name="getBookInfoTest" time="0.034" classname="store.BookInfoTest"/>
  <testcase name="errorExampleTest" time="0.023" classname="failed.ErrorExampleTest">
    <failure type="java.lang.AssertionError" message="返回码错误！">
      <![CDATA[java.lang.AssertionError: 返回码错误！
	at tools.AssertTool.assertEqualsInt(AssertTool.java:24)
	at failed.ErrorExampleTest.errorExampleTest(ErrorExampleTest.java:27)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
... Removed 30 stack frames]]>
    </failure>
  </testcase> <!-- errorExampleTest -->
</testsuite> <!-- getExample -->
